# Generated by Django 6.0.7 on 2026-07-09 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'business hours',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='StaffTimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'staff time off',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='StaffUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'staff unavailability',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='staffworkinghours',
            name='unique_staff_weekday_start_time',
        ),
        migrations.AddConstraint(
            model_name='businesshours',
            constraint=models.UniqueConstraint(fields=('weekday', 'start_time'), name='unique_business_hours_weekday_start_time'),
        ),
        migrations.AddField(
            model_name='stafftimeoff',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to='catalog.staff'),
        ),
        migrations.AddField(
            model_name='staffunavailability',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailability', to='catalog.staff'),
        ),
        migrations.RemoveField(
            model_name='staffworkinghours',
            name='staff',
        ),
        migrations.AddConstraint(
            model_name='staffunavailability',
            constraint=models.UniqueConstraint(fields=('staff', 'weekday', 'start_time'), name='unique_staff_unavailability_weekday_start_time'),
        ),
        migrations.DeleteModel(
            name='StaffWorkingHours',
        ),
    ]
